/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabellerRouteRouteImport } from './routes/labeller/route'
import { Route as ExplorerRouteRouteImport } from './routes/explorer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerIndexRouteImport } from './routes/explorer/index'
import { Route as ExplorerItemIdRouteImport } from './routes/explorer/$itemId'

const LabellerRouteRoute = LabellerRouteRouteImport.update({
  id: '/labeller',
  path: '/labeller',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRouteRoute = ExplorerRouteRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRouteRoute,
} as any)
const ExplorerItemIdRoute = ExplorerItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ExplorerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRouteRouteWithChildren
  '/labeller': typeof LabellerRouteRoute
  '/explorer/$itemId': typeof ExplorerItemIdRoute
  '/explorer/': typeof ExplorerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labeller': typeof LabellerRouteRoute
  '/explorer/$itemId': typeof ExplorerItemIdRoute
  '/explorer': typeof ExplorerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRouteRouteWithChildren
  '/labeller': typeof LabellerRouteRoute
  '/explorer/$itemId': typeof ExplorerItemIdRoute
  '/explorer/': typeof ExplorerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/labeller'
    | '/explorer/$itemId'
    | '/explorer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/labeller' | '/explorer/$itemId' | '/explorer'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/labeller'
    | '/explorer/$itemId'
    | '/explorer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRouteRoute: typeof ExplorerRouteRouteWithChildren
  LabellerRouteRoute: typeof LabellerRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/labeller': {
      id: '/labeller'
      path: '/labeller'
      fullPath: '/labeller'
      preLoaderRoute: typeof LabellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/': {
      id: '/explorer/'
      path: '/'
      fullPath: '/explorer/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
    '/explorer/$itemId': {
      id: '/explorer/$itemId'
      path: '/$itemId'
      fullPath: '/explorer/$itemId'
      preLoaderRoute: typeof ExplorerItemIdRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
  }
}

interface ExplorerRouteRouteChildren {
  ExplorerItemIdRoute: typeof ExplorerItemIdRoute
  ExplorerIndexRoute: typeof ExplorerIndexRoute
}

const ExplorerRouteRouteChildren: ExplorerRouteRouteChildren = {
  ExplorerItemIdRoute: ExplorerItemIdRoute,
  ExplorerIndexRoute: ExplorerIndexRoute,
}

const ExplorerRouteRouteWithChildren = ExplorerRouteRoute._addFileChildren(
  ExplorerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRouteRoute: ExplorerRouteRouteWithChildren,
  LabellerRouteRoute: LabellerRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
