# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
    ASSETS_PATH: /home/jamesg/test_data/naturescan/
    COLLECTIONS_PATH: /home/jamesg/test_data/naturescan/stac/collections.json
    # Ports
    WEB_APP_PORT: 8000
    API_TITILER_PORT: 8001
    API_STAC_PORT: 8002
    API_SEGMENTATION_PORT: 8003
    ASSETS_PORT: 8010

tasks:
    # Local Asset Server
    dev:asset-server:
        desc: Serve assets on http
        cmds:
            - pnpm dlx http-server {{.ASSETS_PATH}} --port {{.ASSETS_PORT}} --cors

    # TiTiler API Server via Docker
    dev:api-titiler:
        desc: Start the TiTiler API server via Docker
        cmds:
            - docker run -p 8001:8001 ghcr.io/developmentseed/titiler:latest uvicorn titiler.application.main:app --host 0.0.0.0 --port 8001

    # TiTiler API Server via Pixi
    # This is helpful if assets are being served locally via asset-server
    # As I couldn't figure out how to get the docker version to work
    # with it
    dev:api-titiler-pixi:
        desc: Start the TiTiler API server via Pixi
        dir: services/api-titiler
        cmds:
            - pixi run dev {{.API_TITILER_PORT}}

    # STAC API
    dev:api-stac:
        desc: Start the STAC API server
        dir: services/api-stac
        cmds:
            - pixi run dev {{.API_STAC_PORT}} {{.COLLECTIONS_PATH}}
        env:
            STAC_FASTAPI_COLLECTIONS_HREF: "{{.COLLECTIONS_PATH }}"

    # Segmentaion API
    dev:api-segmentation:
        desc: Start the segmentation API
        dir: services/api-segmentation
        cmds:
            - pixi run dev {{.API_SEGMENTATION_PORT}}

    # Web App
    dev:web-app:
        desc: Start the web app dev server
        dir: apps/web-app
        cmds:
            - pnpm run dev

    # Caddy HTTPS reverse proxy
    dev:caddy:
        desc: Start Caddy reverse proxy for local HTTPS
        cmds:
            - caddy run --config ./Caddyfile

    # Build API STAC
    build:api-stac:
        desc: "Build STAC API docker file"
        dir: services/api-stac
        cmds:
            - docker build -t api-stac .
            - docker image tag api-stac jmswsc/api-stac
            - docker push jmswsc/api-stac

    # Build API Segmentation
    build:api-segmentation:
        desc: Build segmentation API docker file
        dir: services/api-segmentation
        cmds:
            - docker build -t api-segmentation .
            - docker image tag api-segmentation jmswsc/api-segmentation

    # Build the web app
    build:web-app:
        desc: Build the web app
        dir: apps/web-app
        cmds:
            - docker build -t web-app .
            - docker image tag web-app jmswsc/web-app
            - docker push jmswsc/web-app

    build:
        desc: Build all services
        deps: [build:api-stac, build:web-app]
