#!/usr/bin/env bash
# Export environment variables for TiTiler API

# TiTiler Vars
export TITILER_API_NAME="Naturescan TiTiler"
export TITILER_API_DISABLE_MOSAIC="TRUE"
export TITILER_API_CORS_ORIGINS="*"

# GDAL Vars
export GDAL_HTTP_MERGE_CONSECUTIVE_RANGES="YES"
export GDAL_DISABLE_READDIR_ON_OPEN="EMPTY_DIR"
export CPL_VSIL_CURL_ALLOWED_EXTENSIONS=".tif,.TIF,.tiff"
export GDAL_CACHEMAX="200"
export CPL_VSIL_CURL_CACHE_SIZE="200000000"
export VSI_CACHE="TRUE"
export VSI_CACHE_SIZE="5000000"
export GDAL_BAND_BLOCK_CACHE="HASHSET"
export GDAL_HTTP_MULTIPLEX="YES"
export GDAL_HTTP_VERSION="2"
